### ISSUE TITLE
MTU value not reflected in ifcfg.ww

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf#807]
### Version of Warewulf

What version of Warewulf are you using? Run

```wwctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21" ```

### Expected behavior

MTU size in the node configuration will set the MTU size for the given interface. 

### Actual behavior

While the MTU value for an interface can be set using the node set command it will not change the MTU size of the given interface. 
In fact, the ifcfg.ww file does not contain a sequence for setting the MTU size according to the node configuration.

What actually happened? Why was it incorrect?
MTU size will be ignored.
Please add
```{{ if $netdev.MTU -}}
MTU={{ $netdev.MTU }}
{{ end -}} ```
to the ifcfg.ww default.

<!-- if this is a feature request, you can ignore this next part -->

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

### How did you install Warewulf
Using rpm file for version 4.4

Write here how you installed Warewulf. Eg. RPM, source.

**Comment by anderbubble** [comment]
I think this is fixed in development, but I'll check and confirm.

**Comment by mslacken** [comment]
Its also not reflected in the configuration for network manager

**Comment by BeHom** [comment]
I just check the source code again and MTU setting  still not part of the network configuration files. 
Please...
