### ISSUE TITLE
Tags set in profiles are ignored

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#967]
Pasting in from Slack:

@mslacken  not sure if this is worth creating an issue (edit: it is), hopefully you can spot what I'm doing wrong here. This is in development based on a fresh git pull a couple of hours ago.
I have a template that has this line in it:
```
{{ if .Tags.caddy_email -}}email {{ .Tags.caddy_email }}{{- end }}
```

Then I have set in a profile:
```
  tags:
    caddy_email: 'john.hanks@czbiohub.org'
```

When I then render that template I get no hit/match there and the line is empty for nodes which include this profile, for example:

```
[I am root!@frankie:(bare)::~]# wwctl node list -a svc-vm-globus | grep caddy_email | sed  's/[[:space:]]*$//g' 
  svc-vm-globus  Tags[caddy_email]                     tags-common                   john.hanks@czbiohub.org
```

Clearly the tag is defined via the tags-common profile, but when I render the template:

```
[I am root!@frankie:(bare):wwovl(service-caddy):caddy]# wwctl overlay show -r svc-vm-globus service-caddy /etc/caddy/Caddyfile.ww | grep john.hanks
backupFile: true
writeFile: true
Filename: /etc/caddy/Caddyfile
```

But if I define that tag in the node config, for example:

```[I am root!@frankie:(bare)::~]# wwctl node list -a svc-vm-webgw | grep caddy_email | sed  's/[[:space:]]*$//g' 
  svc-vm-webgw  Tags[caddy_email]                               --                            john.hanks@czbiohub.org
```

The node there svc-vm-webgw overrides the tag with a local value. This renders correctly:
```
[I am root!@frankie:(bare):wwovl(service-caddy):caddy]# wwctl overlay show -r svc-vm-webgw service-caddy /etc/caddy/Caddyfile.ww | grep john.hanks
backupFile: true
writeFile: true
Filename: /etc/caddy/Caddyfile
email john.hanks@czbiohub.org
```

Any idea why it's ignoring the tag if the tag is set via profile instead of directly in the node config? I'm thinking that when I updated to the latest development this morning I broke all my templates that are using a profile to set the tags.

**Comment by anderbubble** [comment]
@mslacken this appears to have been introduced by https://github.com/hpcng/warewulf/pull/949

Can you investigate?

**Comment by mslacken** [comment]
I can confirm this now, as the tags aren't correctly merged back.

**Comment by griznog** [comment]
Updating this as the behavior has changed so that tags from profiles do get merged into the node config, but I'm not allowed to override a tag set in a profile in the node config, e.g. 

 If I set tags as in this `nodes.conf`

```
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
  profile1:
    runtime overlay:
    - overlay1
    - overlay2
    tags:
      p1tag1: bubba
      p1tag2: bubbatwo
  profile2:
    runtime overlay:
    - overlay3
    - overlay2
    tags:
      p2tag1: bubber
      p2tag2: bubbertwo
nodes:
  node-kvm-1:
    profiles:
    - profile1
    - profile2
    tags:
      nodetag: someval
```

Then try to add a profile defined tag to the node it silently fails:
```
[root@corbicula ~]# wwctl node set --tagadd "p2tag2=overriden"  node-kvm-1 
Are you sure you want to modify 1 nodes(s): y
[root@corbicula ~]# wwctl node list -a | grep -E "(Tags)"
  node-kvm-1  Tags[p2tag1]                 profile2  bubber                                                 
  node-kvm-1  Tags[p2tag2]                 profile2  bubbertwo                                              
  node-kvm-1  Tags[nodetag]                --        someval                                                
  node-kvm-1  Tags[nodetag2]               --        someval2                                               
  node-kvm-1  Tags[p1tag1]                 profile1  bubba                                                  
  node-kvm-1  Tags[p1tag2]                 profile1  bubbatwo              
```

But if I manually edit `nodes/conf` and add the tag, the node config looks correct:
```
  node-kvm-1:
    profiles:
    - profile1
    - profile2
    tags:
      p2tag2: overriden
      nodetag: someval
      nodetag2: someval2
```
And the result:

```
[root@corbicula ~]# wwctl node list -a | grep -E "(Tags)"
  node-kvm-1  Tags[p1tag2]                 profile1  bubbatwo                                               
  node-kvm-1  Tags[p2tag1]                 profile2  bubber                                                 
  node-kvm-1  Tags[p2tag2]                 --        overriden                                              
  node-kvm-1  Tags[nodetag]                --        someval                                                
  node-kvm-1  Tags[nodetag2]               --        someval2                                               
  node-kvm-1  Tags[p1tag1]                 profile1  bubba         
```

**Comment by anderbubble** [comment]
@mslacken I just merged #971, which was supposed to fix this. Can you check that it fixed this new behavior, too?

**Comment by griznog** [comment]
Upgrading to latest `main` this morning, it still doesn't let me set the tag in the node if it already exists in a profile:

```
[root@corbicula ~]# wwctl node  list -a | grep "Tags" | sort
  node-kvm-1  Tags[nodetag2]  --        someval2                                               
  node-kvm-1  Tags[nodetag]   --        someval                                                
  node-kvm-1  Tags[p1tag1]    profile1  bubba                                                  
  node-kvm-1  Tags[p1tag2]    profile1  bubbatwo                                               
  node-kvm-1  Tags[p2tag1]    profile2  bubber                                                 
  node-kvm-1  Tags[p2tag2]    profile2  bubbertwo                                              
[root@corbicula ~]# wwctl node set --tagadd='p2tag1=override' node-kvm-1
? Are you sure you want to modify 1 nodes(s)? [y/N] y█
[root@corbicula ~]# wwctl node  list -a | grep "Tags" | sort
  node-kvm-1  Tags[nodetag2]  --        someval2                                               
  node-kvm-1  Tags[nodetag]   --        someval                                                
  node-kvm-1  Tags[p1tag1]    profile1  bubba                                                  
  node-kvm-1  Tags[p1tag2]    profile1  bubbatwo                                               
  node-kvm-1  Tags[p2tag1]    profile2  bubber                                                 
  node-kvm-1  Tags[p2tag2]    profile2  bubbertwo                                              
[root@corbicula ~]# 
```

But it still does the right thing if I manually edit `nodes.conf` and add the tag to the node config:
```
[root@corbicula ~]# vim /etc/warewulf/nodes.conf 
[root@corbicula ~]# wwctl node  list -a | grep "Tags" | sort
  node-kvm-1  Tags[nodetag2]  --        someval2                                               
  node-kvm-1  Tags[nodetag]   --        someval                                                
  node-kvm-1  Tags[p1tag1]    profile1  bubba                                                  
  node-kvm-1  Tags[p1tag2]    profile1  bubbatwo                                               
  node-kvm-1  Tags[p2tag1]    --        override                                               
  node-kvm-1  Tags[p2tag2]    profile2  bubbertwo                                  
```

**Comment by JasonYangShadow** [comment]
I also tested this on the latest main branch, it looks like that `wwctl node set --tagadd` won't overwrite the same tag key if it already exists in the profile. Other non-existing tags are successfully written into the node conf. 
```
root@ubuntu:/home/vagrant/warewulf# wwctl node list -a | grep "Tags"
  n1    Tags[another]   --       tag                                                    
  n1    Tags[email]     default  profile                                                
root@ubuntu:/home/vagrant/warewulf# wwctl node set --tagadd='email=node' n1
Are you sure you want to modify 1 nodes(s): y
root@ubuntu:/home/vagrant/warewulf# wwctl node list -a | grep "Tags"
  n1    Tags[another]   --       tag                                                    
  n1    Tags[email]     default  profile  
```

just to confirm, is the overwritten behavior expected? (i.e., tag existing inside profile should be overwritten with new value passed via `wwctl node set --tagadd=`?)
